image: fedora:latest

build_mingw64:
  stage: build
  script:
    - dnf --quiet --assumeyes install mingw64-gcc mingw64-gcc-c++ mingw64-binutils mingw64-headers mingw64-podofo mingw64-qt5-qtbase mingw64-qt5-qttools mingw64-qt5-qttools-tools cmake make
    - export PKG_CONFIG_LIBDIR="/usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig:/usr/x86_64-w64-mingw32/sys-root/mingw/share/pkgconfig"
    - export PATH=/usr/x86_64-w64-mingw32/bin:$PATH
    - mkdir -p x86_64-w64-mingw32; cd x86_64-w64-mingw32
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-mingw64.cmake -DCMAKE_INSTALL_PREFIX=/usr/x86_64-w64-mingw32/sys-root/mingw
    - make; make install
  artifacts:
    expire_in: 14d
    paths:
      - /usr/x86_64-w64-mingw32/sys-root/mingw
  tags:
    - shared

