name: pdfmixtool
version: '0.3'
summary: An application to split, merge, rotate and mix PDF files
description: |
  PDF Mix Tool is a simple and lightweight application that allows you to split, merge, rotate and mix PDF files.
  It is written in C++ and depends only on Qt 5 and PoDoFo.

grade: stable
confinement: strict

apps:
  pdfmixtool:
    command: desktop-launch $SNAP/usr/bin/pdfmixtool
    plugs:
      - home
      - x11
      - wayland
      - opengl

parts:
  pdfmixtool:
    plugin: cmake
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr]
    source: .
    build-packages:
      - build-essential
      - qtbase5-dev
      - libpodofo-dev
      - qttools5-dev-tools
      - discount
    stage-packages:
      - libpodofo0.9.3
    after: [desktop-qt5]
