name: pdfmixtool
version: '0.3'
summary: An application to split, merge, rotate and mix PDF files
description: |
  PDF Mix Tool is a simple and lightweight application that allows you to split, merge, rotate and mix PDF files.
  It is written in C++ and depends only on Qt 5 and PoDoFo.

grade: stable
confinement: strict

apps:
  pdfmixtool:
    command: desktop-launch $SNAP/usr/bin/pdfmixtool
    plugs:
      - home
      - x11
      - wayland
      - opengl

parts:
  pdfmixtool:
    plugin: cmake
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr]
    source: .
    build-packages:
      - build-essential
      - qtbase5-dev
      - qttools5-dev-tools
      - discount
    after: [desktop-qt5 libpodofo]
  libpodofo:
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DFREETYPE_INCLUDE_DIR=/usr/include/freetype2
      - -DPODOFO_BUILD_SHARED=1
      - -DPODOFO_HAVE_JPEG_LIB=1
      - -DPODOFO_HAVE_PNG_LIB=1
      - -DPODOFO_HAVE_TIFF_LIB=1
      - -DPODOFO_BUILD_LIB_ONLY=1
    source: https://svn.code.sf.net/p/podofo/code/podofo/trunk
    source-type: svn
    build-packages:
      - build-essential
      - liblua5.3
      - libssl1.0.0
      - libfontconfig1
      - libtiffxx5
      - libidn11
      - libjpeg-turbo8
    stage-packages:
      - liblua5.3-dev
      - libssl-dev
      - libfontconfig1-dev
      - libtiffxx5-dev
      - libidn11-dev
      - libjpeg-turbo8-dev
